name: QuickQuake
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip

  # Core científico
  - numpy=1.25.*
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - obspy=1.4.0
  - pyproj
  - h5py
  - pyyaml
  - tqdm
  - requests
  - fsspec

  # PhaseNet (CPU)
  - tensorflow=2.14.*=*cpu*
  - tensorboard=2.14.*

  # Pip: SOLO lo imprescindible (sin seisgo/seisbench)
  - pip:
      - hypoinvpy==0.7.0
      - hypoxpy==0.1.0
      - pyasdf==0.8.1
      - pycwt==0.4.0b0
      - kneed==0.8.5
      - plotly==6.0.1
